version: 2.1
jobs:
    build:
        working_directory: ~/mern-starter
        docker:
            - image: circleci/node:12.18
        steps:
            - checkout
            - run:
                name: Install npm version 6.14.7
                command: 'sudo npm install -g npm@6.14.7'
            - restore_cache:
                key: node-cache-{{ checksum "package-lock.json" }}
            - run:
                name: npm install
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            - run:
                name: npm run build
                command: npm run build
            - run:
                name: npm run lint
                command: npm run lint
